const courseApi = [
  {
    id: 1,
    title: "Python 3 For Offensive PenTest: A Complete Practical Course",
    image: "https://i.ibb.co/HNksYBv/images-2.jpg",
    writter: "Jos Portila",
    rating: "4.6",
    viwer: "1195",
    mainPrice: "84.99",
    disPrice: "16.99",
    type: "Python",
    bestseller: true,
  },
  {
    id: 2,
    title: "2022 Complete Python Bootcamp From Zero to Hero in Python",
    image: "https://i.ibb.co/MNfDs6w/download.jpg",
    writter: "Hussam Kharis",
    rating: "4.5",
    viwer: "795",
    mainPrice: "86.99",
    disPrice: "17.99",
    type: "Python",
    bestseller: false,
  },
  {
    id: 3,
    title: "Taming Big Data with Apache Spark and Python - Hands On!",
    image: "https://i.ibb.co/37vyqt3/images.png",
    writter: "Tim Buchalka",
    rating: "4",
    viwer: "1295",
    mainPrice: "106.99",
    disPrice: "54.99",
    type: "Python",
    bestseller: true,
  },
  {
    id: 4,
    title: "Web Developer Bootcamp with Flask and Python",
    image: "https://i.ibb.co/6vCV1cy/images-3.jpg",
    writter: "Jos sebilta",
    rating: "4.5",
    viwer: "495",
    mainPrice: "66.99",
    disPrice: "12.99",
    type: "Python",
    bestseller: false,
  },
  {
    id: 5,
    title: "Automate the Boring Stuff with Python Programming",
    image: "https://i.ibb.co/6JjzPwS/images-1.jpg",
    writter: "Hussam Kharis",
    rating: "5",
    viwer: "1795",
    mainPrice: "102.99",
    disPrice: "77.99",
    type: "Python",
    bestseller: true,
  },
  {
    id: 6,
    title: "Python 3 For Offensive PenTest: A Complete Practical Course",
    image: "https://i.ibb.co/HNksYBv/images-2.jpg",
    writter: "Infiniti Skill",
    rating: "4.5",
    viwer: "795",
    mainPrice: "44.99",
    disPrice: "23.99",
    type: "Python",
    bestseller: true,
  },
  {
    id: 7,

    title: "Python 3 For Offensive PenTest: A Complete Practical Course",
    image: "https://i.ibb.co/fnQBrZG/836376-8b97-4.jpg",
    writter: "Pyton dev.org",
    rating: "5",
    viwer: "3795",
    mainPrice: "206.99",
    disPrice: "77.99",
    type: "Python",
    bestseller: false,
  },
  {
    id: 8,
    title: "Microsoft Excel 2013 Course Beginners/ Intermediate Training",
    image: "https://i.ibb.co/CMpY1SW/images-3.jpg",
    writter: "infinity skill",
    rating: "5",
    viwer: "5195",
    mainPrice: "306.99",
    disPrice: "201.99",
    type: "Exel",
    bestseller: true,
  },
  {
    id: 9,
    title: "Sharper skills using Microsoft Excel 2010 for business",
    image: "https://i.ibb.co/G7zyHhq/images-4.jpg",
    writter: "exel dev.org",
    rating: "3.5",
    viwer: "695",
    mainPrice: "46.99",
    disPrice: "12.99",
    type: "Exel",
    bestseller: false,
  },
  {
    id: 10,
    title: "Advanced Excel - Beginner to Ninja level (includes Charts)",
    image: "https://i.ibb.co/HCVRcpb/images.jpg",
    writter: "Tim Buchalka",
    rating: "4",
    viwer: "1495",
    mainPrice: "86.99",
    disPrice: "34.99",
    type: "Exel",
    bestseller: true,
  },
  {
    id: 11,
    title: "Step-by-step Spreadsheets for Absolute Beginners",
    image: "https://i.ibb.co/4W2P7VJ/images-2.jpg",
    writter: "infinity skill",
    rating: "4.5",
    viwer: "1495",
    mainPrice: "36.99",
    disPrice: "12.07",
    type: "Exel",
    bestseller: false,
  },
  {
    id: 12,
    title: "Excel Shortcuts, Excel Tips, Excel Tricks - Excel Skills!",
    image: "https://i.ibb.co/26Xtszc/download.jpg",
    writter: "exel.org",
    rating: "5",
    viwer: "1795",
    mainPrice: "102.99",
    disPrice: "77.99",
    type: "Exel",
    bestseller: true,
  },
  {
    id: 13,
    title: "The Ultimate Excel Programmer Course",
    image: "https://i.ibb.co/7gcsQW9/download-2.jpg",
    writter: "Infiniti Skill",
    rating: "4.5",
    viwer: "795",
    mainPrice: "74.99",
    disPrice: "33.99",
    type: "Exel",
    bestseller: true,
  },
  {
    id: 14,
    title: "Master Microsoft Excel, Outlook and Word 2013 - 26 Hours",
    image: "https://i.ibb.co/Yh8K5Kk/images-1.jpg",
    writter: "exel dev.org",
    rating: "5",
    viwer: "3795",
    mainPrice: "206.99",
    disPrice: "77.99",
    type: "Exel",
    bestseller: true,
  },

  {
    id: 15,
    title: "The Complete 2020 Fullstack Web Developer Course",
    image: "https://i.ibb.co/k0GwgJS/images-2.jpg",
    writter: "infinity skill",
    rating: "5",
    viwer: "5195",
    mainPrice: "306.99",
    disPrice: "201.99",
    type: "Web Development",
    bestseller: true,
  },
  {
    id: 16,
    title: "The Complete 2020 Fullstack Web Developer Course",
    image: "https://i.ibb.co/X7qQpkg/images-3.jpg",
    writter: "exel dev.org",
    rating: "3.5",
    viwer: "695",
    mainPrice: "46.99",
    disPrice: "12.99",
    type: "Web Development",
    bestseller: false,
  },
  {
    id: 17,
    title: "The Complete 2020 Fullstack Web Developer Course",
    image: "https://i.ibb.co/gW37QM9/images.png",
    writter: "Tim Buchalka",
    rating: "4",
    viwer: "1495",
    mainPrice: "86.99",
    disPrice: "34.99",
    type: "Web Development",
    bestseller: true,
  },
  {
    id: 18,
    title: "The Complete 2020 Fullstack Web Developer Course",
    image: "https://i.ibb.co/1fGPdNt/download.png",
    writter: "infinity skill",
    rating: "4.5",
    viwer: "1495",
    mainPrice: "36.99",
    disPrice: "12.07",
    type: "Web Development",
    bestseller: false,
  },
  {
    id: 19,
    title: "The Complete 2020 Fullstack Web Developer Course",
    image: "https://i.ibb.co/M89G6Kj/download-1.png",
    writter: "exel.org",
    rating: "5",
    viwer: "1795",
    mainPrice: "102.99",
    disPrice: "77.99",
    type: "Web Development",
    bestseller: true,
  },
  {
    id: 20,
    title: "The Complete 2020 Fullstack Web Developer Course",
    image: "https://i.ibb.co/VHH4fC0/images-4.jpg",
    writter: "Infiniti Skill",
    rating: "4.5",
    viwer: "795",
    mainPrice: "74.99",
    disPrice: "33.99",
    type: "Web Development",
    bestseller: true,
  },
  {
    id: 21,
    title: "The Complete 2020 Fullstack Web Developer Course",
    image: "https://i.ibb.co/Z2wMnmH/images-1.jpg",
    writter: "exel dev.org",
    rating: "5",
    viwer: "3795",
    mainPrice: "206.99",
    disPrice: "77.99",
    type: "Web Development",
    bestseller: true,
  },

  {
    id: 22,
    title: "JavaScript: Understanding the Weird Parts",
    image: "https://i.ibb.co/jf6SwBY/images.png",
    writter: "infinity skill",
    rating: "5",
    viwer: "5195",
    mainPrice: "306.99",
    disPrice: "201.99",
    type: "Javascript",
    bestseller: true,
  },
  {
    id: 23,
    title: "Javascript for Beginners Learn by Doing Practical Exercises",
    image: "https://i.ibb.co/y47BGYs/images.jpg",
    writter: "exel dev.org",
    rating: "3.5",
    viwer: "695",
    mainPrice: "46.99",
    disPrice: "12.99",
    type: "Javascript",
    bestseller: false,
  },
  {
    id: 24,
    title: "vJavaScript: Understanding the Weird Parts",
    image: "https://i.ibb.co/8bz6Bzx/images-2.jpg",
    writter: "Tim Buchalka",
    rating: "4",
    viwer: "1495",
    mainPrice: "86.99",
    disPrice: "34.99",
    type: "Javascript",
    bestseller: true,
  },
  {
    id: 25,
    title: "Javascript for Beginners Learn by Doing Practical Exercises",
    image: "https://i.ibb.co/pyc311b/images-1.jpg",
    writter: "infinity skill",
    rating: "4.5",
    viwer: "1495",
    mainPrice: "36.99",
    disPrice: "12.07",
    type: "Javascript",
    bestseller: false,
  },
  {
    id: 26,
    title: "JavaScript: Understanding the Weird Parts",
    image: "https://i.ibb.co/4dYCdNk/download.png",
    writter: "exel.org",
    rating: "5",
    viwer: "1795",
    mainPrice: "102.99",
    disPrice: "77.99",
    type: "Javascript",
    bestseller: true,
  },
  {
    id: 27,
    title: "Javascript for Beginners Learn by Doing Practical Exercises",
    image: "https://i.ibb.co/WDCWFxB/download-2.jpg",
    writter: "Infiniti Skill",
    rating: "4.5",
    viwer: "795",
    mainPrice: "74.99",
    disPrice: "33.99",
    type: "Javascript",
    bestseller: true,
  },
  {
    id: 28,
    title: "JavaScript: Understanding the Weird Parts",
    image: "https://i.ibb.co/bPZDX96/download-1.png",
    writter: "exel dev.org",
    rating: "5",
    viwer: "3795",
    mainPrice: "206.99",
    disPrice: "77.99",
    type: "Javascript",
    bestseller: true,
  },

  {
    id: 29,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    image: "https://i.ibb.co/3sMrNvn/images-4.jpg",
    writter: "infinity skill",
    rating: "5",
    viwer: "5195",
    mainPrice: "306.99",
    disPrice: "201.99",
    type: "Data Science",
    bestseller: true,
  },
  {
    id: 30,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    image: "https://i.ibb.co/6YZn0Zy/images.jpg",
    writter: "exel dev.org",
    rating: "3.5",
    viwer: "695",
    mainPrice: "46.99",
    disPrice: "12.99",
    type: "Data Science",
    bestseller: false,
  },
  {
    id: 31,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    image: "https://i.ibb.co/PYKvMvz/images-5.jpg",
    writter: "Tim Buchalka",
    rating: "4",
    viwer: "1495",
    mainPrice: "86.99",
    disPrice: "34.99",
    type: "Data Science",
    bestseller: true,
  },
  {
    id: 32,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    image: "https://i.ibb.co/LrDDRL7/images-3.jpg",
    writter: "infinity skill",
    rating: "4.5",
    viwer: "1495",
    mainPrice: "36.99",
    disPrice: "12.07",
    type: "Data Science",
    bestseller: false,
  },
  {
    id: 33,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    image: "https://i.ibb.co/WKxfFF0/images-2.jpg",
    writter: "exel.org",
    rating: "5",
    viwer: "1795",
    mainPrice: "102.99",
    disPrice: "77.99",
    type: "Data Science",
    bestseller: true,
  },
  {
    id: 34,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    image: "https://i.ibb.co/swz18bp/images-1.jpg",
    writter: "Infiniti Skill",
    rating: "4.5",
    viwer: "795",
    mainPrice: "74.99",
    disPrice: "33.99",
    type: "Data Science",
    bestseller: true,
  },
  {
    id: 35,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    image: "https://i.ibb.co/bL5bn1x/download-2.jpg",
    writter: "exel dev.org",
    rating: "5",
    viwer: "3795",
    mainPrice: "206.99",
    disPrice: "77.99",
    type: "Data Science",
    bestseller: true,
  },

  {
    id: 36,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    image: "https://i.ibb.co/7VP4DXp/images.png",
    writter: "infinity skill",
    rating: "5",
    viwer: "5195",
    mainPrice: "306.99",
    disPrice: "201.99",
    type: "AWS Certification",
    bestseller: true,
  },
  {
    id: 37,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    image: "https://i.ibb.co/nsbD6zs/images.jpg",
    writter: "exel dev.org",
    rating: "3.5",
    viwer: "695",
    mainPrice: "46.99",
    disPrice: "12.99",
    type: "AWS Certification",
    bestseller: false,
  },
  {
    id: 38,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    image: "https://i.ibb.co/zRmzTpF/images-2.jpg",
    writter: "Tim Buchalka",
    rating: "4",
    viwer: "1495",
    mainPrice: "86.99",
    disPrice: "34.99",
    type: "AWS Certification",
    bestseller: true,
  },
  {
    id: 39,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    image: "https://i.ibb.co/sbsRT3n/images-1.png",
    writter: "infinity skill",
    rating: "4.5",
    viwer: "1495",
    mainPrice: "36.99",
    disPrice: "12.07",
    type: "AWS Certification",
    bestseller: false,
  },
  {
    id: 40,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    image: "https://i.ibb.co/KF172DX/images-1.jpg",
    writter: "exel.org",
    rating: "5",
    viwer: "1795",
    mainPrice: "102.99",
    disPrice: "77.99",
    type: "AWS Certification",
    bestseller: true,
  },
  {
    id: 41,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    image: "https://i.ibb.co/qyx7Y1J/download-2.jpg",
    writter: "Infiniti Skill",
    rating: "4.5",
    viwer: "795",
    mainPrice: "74.99",
    disPrice: "33.99",
    type: "AWS Certification",
    bestseller: true,
  },
  {
    id: 42,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    image: "https://i.ibb.co/1KCZ9dc/download-1.jpg",
    writter: "exel dev.org",
    rating: "5",
    viwer: "3795",
    mainPrice: "206.99",
    disPrice: "77.99",
    type: "AWS Certification",
    bestseller: true,
  },

  {
    id: 43,
    title: "Art Fundamentals: Foundations of Painting and Drawing Course",
    image: "https://i.ibb.co/Fb3YXW1/images.jpg",
    writter: "infinity skill",
    rating: "5",
    viwer: "5195",
    mainPrice: "306.99",
    disPrice: "201.99",
    type: "Drawing",
    bestseller: true,
  },
  {
    id: 44,
    title: "Art Fundamentals: Foundations of Painting and Drawing Course",
    image: "https://i.ibb.co/SBbW6f5/images-6.jpg",
    writter: "exel dev.org",
    rating: "3.5",
    viwer: "695",
    mainPrice: "46.99",
    disPrice: "12.99",
    type: "Drawing",
    bestseller: false,
  },
  {
    id: 45,
    title: "Art Fundamentals: Foundations of Painting and Drawing Course",
    image: "https://i.ibb.co/MGL5vy2/images-5.jpg",
    writter: "Tim Buchalka",
    rating: "4",
    viwer: "1495",
    mainPrice: "86.99",
    disPrice: "34.99",
    type: "Drawing",
    bestseller: true,
  },
  {
    id: 46,
    title: "Art Fundamentals: Foundations of Painting and Drawing Course",
    image: "https://i.ibb.co/8dj9DNC/images-4.jpg",
    writter: "infinity skill",
    rating: "4.5",
    viwer: "1495",
    mainPrice: "36.99",
    disPrice: "12.07",
    type: "Drawing",
    bestseller: false,
  },
  {
    id: 47,
    title: "Art Fundamentals: Foundations of Painting and Drawing Course",
    image: "https://i.ibb.co/92vqFww/images-3.jpg",
    writter: "exel.org",
    rating: "5",
    viwer: "1795",
    mainPrice: "102.99",
    disPrice: "77.99",
    type: "Drawing",
    bestseller: true,
  },
  {
    id: 48,
    title: "Art Fundamentals: Foundations of Painting and Drawing Course",
    image: "https://i.ibb.co/m820Q1b/images-1.jpg",
    writter: "Infiniti Skill",
    rating: "4.5",
    viwer: "795",
    mainPrice: "74.99",
    disPrice: "33.99",
    type: "Drawing",
    bestseller: true,
  },
  {
    id: 49,
    title: "Art Fundamentals: Foundations of Painting and Drawing Course",
    image: "https://i.ibb.co/ZzMkXqW/download.jpg",
    writter: "exel dev.org",
    rating: "5",
    viwer: "3795",
    mainPrice: "206.99",
    disPrice: "77.99",
    type: "Drawing",
    bestseller: true,
  },
];

export default courseApi;