const menuData = [
  "Development",
  "Business",
  "Finance And Accounting",
  "IT & Software",
  "Office Productivity",
  "design",
  "Marketing",
  "Lifestyle",
  "Photography & Video",
  "Health & Fitness",
  "Music",
];

const nestedMenuData = [
  { title: "Web Development", type: "Development" },
  { title: "Data Science", type: "Development" },
  { title: "Mobile Development", type: "Development" },
  { title: "Software Development Tools", type: "Development" },
  { title: "Software Tasting", type: "Development" },
  { title: "Software Engineering", type: "Development" },
  { title: "DateBase Design & Development", type: "Development" },
  { title: "Entrepreneurship", type: "Business" },
  { title: "Communication", type: "Business" },
  { title: "Management", type: "Business" },
  { title: "Sales", type: "Business" },
  { title: "Business Raw", type: "Business" },
  { title: "Industry", type: "Business" },
  { title: "Media", type: "Business" },
  { title: "Sales", type: "Business" },
  { title: "Business Raw", type: "Business" },
  { title: "Industry", type: "Business" },
  { title: "Media", type: "Business" },
  { title: "Accounting & Bookkeeping", type: "Finance And Accounting" },
  { title: "Economics", type: "Finance And Accounting" },
  { title: "Finace", type: "Finance And Accounting" },
  { title: "Taxes", type: "Finance And Accounting" },
  { title: "Business Raw", type: "Finance And Accounting" },
  { title: "Entrepreneurship", type: "Finance And Accounting" },
  { title: "Media", type: "Finance And Accounting" },
  { title: "Sales", type: "Finance And Accounting" },
  { title: "Business Raw", type: "Finance And Accounting" },
  { title: "Communication", type: "Finance And Accounting" },
  { title: "Media", type: "Finance And Accounting" },
  { title: "IT Certification", type: "IT & Software" },
  { title: "Network", type: "IT & Software" },
  { title: "Hardware", type: "IT & Software" },
  { title: "Operating System", type: "IT & Software" },
  { title: "IT & Software", type: "IT & Software" },
  { title: "Microsoft", type: "Office Productivity" },
  { title: "Apple", type: "Office Productivity" },
  { title: "Google", type: "Office Productivity" },
  { title: "Sap", type: "Office Productivity" },
  { title: "Oracle", type: "Office Productivity" },
  { title: "Others Office Productivity", type: "Office Productivity" },
  { title: "Web Design", type: "design" },
  { title: "Communication", type: "design" },
  { title: "Management", type: "design" },
  { title: "Databese Design", type: "design" },
  { title: "Business Raw", type: "design" },
  { title: "Industry", type: "design" },
  { title: "Fashion", type: "design" },
  { title: "Graphic Design", type: "design" },
  { title: "Business Raw", type: "design" },
  { title: "Business Raw", type: "Marketing" },
  { title: "Industry", type: "Marketing" },
  { title: "Media", type: "Marketing" },
  { title: "Accounting & Bookkeeping", type: "Marketing" },
  { title: "Economics", type: "Marketing" },
  { title: "Finace", type: "Marketing" },
  { title: "Media", type: "Lifestyle" },
  { title: "Sales", type: "Lifestyle" },
  { title: "Business Raw", type: "Lifestyle" },
  { title: "Communication", type: "Lifestyle" },
  { title: "Media", type: "Lifestyle" },
  { title: "IT Certification", type: "Lifestyle" },
  { title: "Network", type: "Lifestyle" },
  { title: "Gaming", type: "Lifestyle" },
  { title: "Accounting & Bookkeeping", type: "Photography & Video" },
  { title: "Economics", type: "Photography & Video" },
  { title: "Finace", type: "Photography & Video" },
  { title: "Taxes", type: "Photography & Video" },
  { title: "Business Raw", type: "Photography & Video" },
  { title: "Entrepreneurship", type: "Photography & Video" },
  { title: "Media", type: "Photography & Video" },
  { title: "Sales", type: "Photography & Video" },
  { title: "Business Raw", type: "Photography & Video" },
  { title: "Finace", type: "Health & Fitness" },
  { title: "Taxes", type: "Health & Fitness" },
  { title: "Business Raw", type: "Health & Fitness" },
  { title: "Entrepreneurship", type: "Health & Fitness" },
  { title: "Media", type: "Health & Fitness" },
  { title: "Instruments", type: "Music" },
  { title: "Music Production", type: "Music" },
  { title: "Vocal", type: "Music" },
  { title: "Music Software", type: "Music" },
  { title: "Others Music", type: "Music" },
];
export default menuData;
export { nestedMenuData };
